# Generated by Django 2.1 on 2018-08-09 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='ended_on',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='started_on',
        ),
    ]
